name: Rust
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  FACTORIO_USERNAME: ${{ secrets.FACTORIO_USERNAME }}
  FACTORIO_TOKEN: ${{ secrets.FACTORIO_TOKEN }}

jobs: 
  test:
    name: Cargo Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Cargo target cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-carg
      - 
        name: Purge old caches
        uses: MyAlbum/purge-cache@v2
        with:
          accessed: true # Purge caches by their last accessed time (default)
          created: false # Purge caches by their created time (default)
          max-age: 604800 # Leave only caches accessed in the last 7 days (default)
      -
        name: Build
        run: cargo build --verbose
      -
        name: Tests
        run: cargo test --verbose
