name: Rust
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  test: 
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Build
        run: cargo build --verbose
      -
        name: Tests
        run: cargo test --verbose
